In [1]:
#Import Libraries
import pandas as pd
import numpy as np

In [2]:
#Load dataset
df = pd.read_csv(r'C:\Users\ADMIN\Downloads\archive\retail_sales_dataset.csv')

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,11/24/2023,CUST001,Male,34,Beauty,3,50,150
1,2,2/27/2023,CUST002,Female,26,Clothing,2,500,1000
2,3,1/13/2023,CUST003,Male,50,Electronics,1,30,30
3,4,5/21/2023,CUST004,Male,37,Clothing,1,500,500
4,5,5/6/2023,CUST005,Male,30,Beauty,2,50,100

In [3]:
#Basic info
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [4]:
#Check Missing Values
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [5]:
#Handle Missing Values
df['Price per Unit'] = df['Price per Unit'].fillna(df['Price per Unit'].mean())
df['Quantity'] = df['Quantity'].fillna(0)

In [6]:
#Remove Duplicates
df.duplicated().sum()

df = df.drop_duplicates()

In [7]:
#Clean Column Names
df.columns = df.columns.str.lower().str.strip()

df.columns

Index(['transaction id', 'date', 'customer id', 'gender', 'age',
       'product category', 'quantity', 'price per unit', 'total amount'],
      dtype='object')

In [8]:
#Fix Data Types
df['date'] = pd.to_datetime(df['date'])

df['quantity'] = df['quantity'].astype(int)
df['price per unit'] = df['price per unit'].astype(float)

In [9]:
#Create New Columns
df['total_sales'] = df['quantity'] * df['price per unit']

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
df['weekday'] = df['date'].dt.day_name()

In [10]:
#Validate Data
df.head()
df.describe()

,transaction id,date,age,quantity,price per unit,total amount,total_sales,year,month,day,hour
count,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0
mean,500.500000,2023-07-03 00:25:55.200000256,41.39200,2.514000,179.890000,456.000000,456.000000,2023.002000,6.549000,15.310000,0.0
min,1.000000,2023-01-01 00:00:00,18.00000,1.000000,25.000000,25.000000,25.000000,2023.000000,1.000000,1.000000,0.0
25%,250.750000,2023-04-08 00:00:00,29.00000,1.000000,30.000000,60.000000,60.000000,2023.000000,4.000000,7.000000,0.0
50%,500.500000,2023-06-29 12:00:00,42.00000,3.000000,50.000000,135.000000,135.000000,2023.000000,6.000000,15.000000,0.0
75%,750.250000,2023-10-04 00:00:00,53.00000,4.000000,300.000000,900.000000,900.000000,2023.000000,10.000000,23.000000,0.0
max,1000.000000,2024-01-01 00:00:00,64.00000,4.000000,500.000000,2000.000000,2000.000000,2024.000000,12.000000,31.000000,0.0
std,288.819436,NaN,13.68143,1.132734,189.681356,559.997632,559.997632,0.044699,3.452755,8.871674,0.0

In [11]:
# Total revenue
print("Total Sales:", df['total_sales'].sum())

# Top products
df.groupby('product category')['total_sales'].sum().sort_values(ascending=False).head()

Total Sales: 456000.0

product category
Electronics    156905.0
Clothing       155580.0
Beauty         143515.0
Name: total_sales, dtype: float64

In [12]:
#Save Cleaned Data
df.to_csv('cleaned_retail_data.csv', index=False)

In [13]:
#check File Location
import os
os.getcwd()

'C:\\Users\\ADMIN\\Downloads'